import "oaidl.idl";
import "ocidl.idl";

[object, uuid(c1e415cd-c560-43a6-9437-d1622ff08b6c), pointer_default(unique)]
interface IMySplashOutputDev : IUnknown {
	[id(1), propget] HRESULT BitmapWidth([out, retval] int *prv);
	[id(2), propget] HRESULT BitmapHeight([out, retval] int *prv);
	[id(3), propget, local] HRESULT DataPtr([out, retval] void **ppv);
};

[object, uuid(e15697b8-9a72-415c-bf50-3c9e59d58160), pointer_default(unique)]
interface IMyPDFDoc : IUnknown {
	[id(1)] HRESULT isOk([out, retval] BOOL *prv);
	[id(2)] HRESULT getNumPages([out, retval] int *prv);

	[id(4)] HRESULT getPageMediaWidth(int page, [out, retval] double *prv);
	[id(5)] HRESULT getPageMediaHeight(int page, [out, retval] double *prv);
	[id(6)] HRESULT getPageCropWidth(int page, [out, retval] double *prv);
	[id(7)] HRESULT getPageCropHeight(int page, [out, retval] double *prv);
	[id(8)] HRESULT getPageRotate(int page, [out, retval] int *prv);
	[id(9)] HRESULT displayPage(int page, double hDPI, double vDPI, int rotate, BOOL useMediaBox, BOOL crop, BOOL printing, [out, retval] IMySplashOutputDev **pprv);
	[id(10), local] HRESULT savePageAs(BSTR name, int page);
};

[object, uuid(acb65d57-dc88-4d06-916e-295b91c384f1), pointer_default(unique)]
interface IMyPoppler : IUnknown {
	[id(1)] HRESULT NewPDFDoc(BSTR fileName, [out, retval] IMyPDFDoc **ppDoc);
	[id(2)] HRESULT NewGlobalParams(BSTR baseDir);
};

[uuid(787992eb-f9d7-4d23-8218-3ea98c851a3b), version(1.0)]
library poppler2com {
	[uuid(57f30b72-7211-48d6-b28c-4c70e958c166)]
	coclass MyPoppler {
		interface IMyPoppler;
	};
};
